### ISSUE TITLE
Set variable Clicks per step 

### ISSUE THREAD

**Issue by lasalillo** [LennartHennigs/ESPRotary#12]
Hi, 
i see the Clicks per step is static and defined at the beginning.
would it be possible to change it based on some actions?
i mean without to break the counter.
for example, if i press the encoder button, clicks per step is 1, else is 4.
thanks

**Comment by LennartHennigs** [comment]
Hi, the step size is meant for different types of encoders. Some add 3 or 4 per click. This is not ment as a “speed” setting. 

What would you use a variable setting for?

**Comment by lasalillo** [comment]
Hi Lennart, 
my idea is for typical 24 pulses encoders, i like precision but sometimes i want to go from A to B quickly, in this case i can adjust the encoder from 4 to 1 click per step, and the transition from A to B is quick and smooth. I could do the same afterwards just multiplying the result value by 4 but i don't get a smooth transition.
Does it make sense?

**Comment by LennartHennigs** [comment]
Yes, makes sense! 
Will update the library in the next couple of days.
Cheers and thanks for the input.

**Comment by lasalillo** [comment]
Cool, thank you so much.

**Comment by LennartHennigs** [comment]
Small comment to this. I added a function to set the number of clicks.
The encoder I tested with, has usually a for clicks per step setting. To speed it up I can now go down to 1.
Thus I decrease the number of steps, not increase.
