### ISSUE TITLE
new bug (?)

### ISSUE THREAD

**Issue by ab-it** [LennartHennigs/ESPRotary#16]
https://github.com/LennartHennigs/ESPRotary/blob/34581067508e8ce7f1f139441fb86798ac083fa9/src/ESPRotary.cpp#L53

I believe multiplying another time by steps_per_click is wrong. Var last_position is already multiplied and then position needs to equal last_position.

**Comment by LennartHennigs** [comment]
yes, you are right. fixed it!
thx!
