### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ab-it** [LennartHennigs/ESPRotary#17]
https://github.com/LennartHennigs/ESPRotary/blob/59d5476a53ce227e44117792483318e8be908e75/src/ESPRotary.cpp#L47

This function may change the current position. I wonder if there should be a call back.

E.g.

  if (p > upper_bound) {
    last_position = upper_bound * steps_per_click;
  } else {
    last_position = (lower_bound > p) ? lower_bound * steps_per_click : p;
  }
  direction = 0;
  if (position != last_position) {
    position = last_position;
    if (change_cb != NULL) change_cb (*this);
  }

**Comment by LennartHennigs** [comment]
Good point! Added it, too. (You had a run, didn't you.) Thanks again!
