### ISSUE TITLE
control reaches end of non-void function

### ISSUE THREAD

**Issue by ab-it** [LennartHennigs/ESPRotary#18]
https://github.com/LennartHennigs/ESPRotary/blob/59d5476a53ce227e44117792483318e8be908e75/src/ESPRotary.cpp#L77

Currently this function cannot return anything else than left or right. However, the compiler doesn't know this and raises a warning. If, as I did, warnings are treated as errors then the compilers quits.

Three possible fixes:
1: exit function with: assert(false);                        // tell the compiler this cannot be reached
2: exit function with: return "ERROR";                  // should never happen
3: 
  if (direction == RE_LEFT) {
    return "LEFT";
  } else {          // if not left, must be right
    return "RIGHT";
  }

**Comment by LennartHennigs** [comment]
Thx! I will include this in the next release.
