### ISSUE TITLE
reset with parameter doesn't work

### ISSUE THREAD

**Issue by ab-it** [LennartHennigs/ESPRotary#19]
https://github.com/LennartHennigs/ESPRotary/blob/59d5476a53ce227e44117792483318e8be908e75/src/ESPRotary.cpp#L51

p needs to be multiplied by steps_per_click:

 last_position = (lower_bound > p) ? lower_bound * steps_per_click : p * steps_per_click;

**Comment by LennartHennigs** [comment]
Thx for pointing this out. Fixed it!
