### ISSUE TITLE
Suggestion: add initial value

### ISSUE THREAD

**Issue by ab-it** [LennartHennigs/ESPRotary#20]
https://github.com/LennartHennigs/ESPRotary/blob/59d5476a53ce227e44117792483318e8be908e75/src/ESPRotary.cpp#L12

At startup (and at reset, but that is handled by the calling program) it makes sense to be able to define the reset value.  Currently it is 0, which makes sense for halfway -32768 and +32768. But I am setting +5 to +35, and a reset value of +20.

May I suggest to add init_pos (or def_pos):
in ESProtary.c
ESPRotary::ESPRotary(int pin1, int pin2, int steps_per_click /* = 1 */, int lower_bound /* = -32768 */, int upper_bound /* = 32768 */, int init_pos /* = 0 */) {
...
  loop();
  resetPosition(init_pos);
  last_read_ms = 0;

in ESProtary.h
 public:
    ESPRotary(int pin1, int pin2, int steps_per_click = 1, int lower_bound = -32768, int upper_bound = 32768, int init_pos = 0);

and of course in the documentation

**Comment by LennartHennigs** [comment]
Hey, good point, will add it to the code!
Thx!
