### ISSUE TITLE
Question - Not an issue - but what does "last_read_ms = 0;" do

### ISSUE THREAD

**Issue by ornea** [LennartHennigs/ESPRotary#26]
Thanks for sharing your work.

I dont think I am implementing your library correctly so I am having a closer look to see what is going on in the code.

I am struggling to understand (library's in general) why the unsigned long variable last_read_ms  is declared.

Cheers 

info
My target is esp8266 and have tried to implement velocity control i.e. if there is a change in a short time make a big change to the range.

**Comment by LennartHennigs** [comment]
Hey ornea,
thanks for asking. You found a variable that I no longer use.
I'll remove it in the next release.
Thanks for pointing it out :-)

Best
l.
