### ISSUE TITLE
Not working with the delay() function in the main loop

### ISSUE THREAD

**Issue by waihankan** [LennartHennigs/ESPRotary#29]
Hi, the examples were working fine until I add a delay in my main loop. I guess the code doesn't work with the delay function. Is it true? If so how can I implement it in another way?

**Comment by LennartHennigs** [comment]
Well, if you add a delay to your loop, the loop() function of the Rotary gets delayed, too. 

Google "non blocking delay Arduino" and take a look at the Ticker library. These options won't block your main loop and allow you to run code after a certain time frame.
