### ISSUE TITLE
1 turn and 4 output

### ISSUE THREAD

**Issue by beicnet** [LennartHennigs/ESPRotary#3]
I just tried your library with the complete example (with button), but I got a weird output:

```
Simple Counter
RIGHT
1
RIGHT
2
RIGHT
3
RIGHT
4
```
Turned the encoder one time and got 4 output value.

I'm using WeMos D1 mini with KY-040, Arduino IDE v1.8.2

**Comment by LennartHennigs** [comment]
Hi,
I think this is due to the type of encoder. 
You can now define in the constructor the number of clicks supposed to happen on a single turn.
