### ISSUE TITLE
Nit-picky

### ISSUE THREAD

**Issue by Jim-2249** [LennartHennigs/ESPRotary#30]
Nice state-machine implementation! 

A few questions which probably don't affect operation:
* unsigned long last_read_ms; is only declared and assigned in the instance creation. It is never used. Should it be removed?
* pin1 and pin2 are declared as int. Would byte be a better choice for space?

* void ESPRotary::loop() contains
  int s = state & 3;
Maybe make "s" a byte? It's range would appear to be limited to 0-15. Since s is always assigned to the byte variable "state", perhaps just use state and skip "s"?

(added with edit)
* int steps_per_click: It would seem rather unlikely that this would be negative and that the value would be over 127 / 255. Make it a int8_t or uint8_t? 

Save nine bytes of RAM!

The default for the ESPRotary constructor are int lower_bound = INT16_MIN, int upper_bound = INT16_MAX. INT16_MAX is negative 1 for an int. Was this your intention? Probably not much of an issue as most would would set their own bounds.

Thanks for making ESPRotary available!

Cheers -Jim

**Comment by LennartHennigs** [comment]
Hey Jim,
sorry for the late reply and thanks for the feedback. 
Was weeding out things in some other Arduino code...

I removed `last_read_ms`, turned a few `ints` into `bytes`.
The upper / lower bounds were suggested in [this issue](https://github.com/LennartHennigs/ESPRotary/issues/15).

I pushed these changes plus a few smaller ones as well. I will release them in a few days after I tested everything again.

Cheers
l.
