### ISSUE TITLE
direrction sensing issue

### ISSUE THREAD

**Issue by larryl79** [LennartHennigs/ESPRotary#33]
Hi,

I've trying your rotary + button example.
env: ESP32 doit V1 + rotary switch (HW-040 module)

#define ROTARY_PIN1  4        // CLK
#define ROTARY_PIN2  15       // DT

button is working fine, but the direction sensing is very unstable. turning "right" gives "right" with 1-1 random "left".
another case, turning "left" gives "right" with random 1-1 "left"
rotary switch is brand new, never used before.

what's te issue?

**Comment by LennartHennigs** [comment]
Hey Larry,
I don't really know, can only guess from here. 
A reason could be the number of step you defined in your code. Some models use more than one click for a single step. 
Try adjusting that.

**Comment by larryl79** [comment]
Sorry I completely forgot about this case.
It resolved with 10uf capacitors for debouncing an the A and B pin.
