### ISSUE TITLE
Issue? / not issue? esp32 LEFT direction

### ISSUE THREAD

**Issue by Sentinel8000** [LennartHennigs/ESPRotary#35]
Im using Arduino IDE esp core 2.0.2, this is the first library for my rotary encoder what working well, but..not fully. If im insert the button example parts into my code, click!, restart and right working well, but the left reaction slow, i need make 1-2 turns till will be visible on Serial monitor and sometimes jumping displaying to RIGHT direction.

The example working standalone well. What can generate this problem if not issue?, i have tryed on more pins.

thank you

**Comment by LennartHennigs** [comment]
Hey, without the encoder I cannot really reproduce your problem. 
Maybe try out a different click setting. Cheaper encoder do use a different setting .That might be the problem.
