### ISSUE TITLE
Finding RPM using simplepollrotator example

### ISSUE THREAD

**Issue by MrWns14** [LennartHennigs/ESPRotary#41]
hi, sorry if this is out of question, im new in coding and sorry for my bad english.
im trying to find RPM of my shaft using lpd3806(400ppr) encoder. im using the example of simplepollrotator.
i set an experiment where i rotate the shaft for 1min and get 2270 value in the serial monitor.

Can i know what is the 2270 value stand for? is it in pulse per second or baudrate or something else?
2.By any chance, do u know how? because im quite lost . there a formular i find where rpm=pulse*60second/ppr. but i dindt understand and not sure if the value 2270 stand for pulse.

again im really sorry if this is out of question because i cant find the answer online and im stuck and cannot proceed with the calculation.

Thank you very much sir! im really really appreciate if u could help me with my problem , thank you sir

**Comment by LennartHennigs** [comment]
Hello, this is not a question pertaining to my library. I am sorry, but I cannot help you with your own programming tasks. 

But there are examples online for your type of encoder. This was for example the first hit on Google: http://domoticx.com/sensor-lpd3806-optical-rotary-encoder/

It even contains example code. 
Start there. Good luck.

**Comment by MrWns14** [comment]
> Hello, this is not a question pertaining to my library. I am sorry, but I cannot help you with your own programming tasks.
> 
> But there are examples online for your type of encoder. This was for example the first hit on Google: http://domoticx.com/sensor-lpd3806-optical-rotary-encoder/
> 
> It even contains example code. Start there. Good luck.

Hi sir. Im very2 sorry , im mistaken the example name. M
It is simple counter example. Truelyy sorry.  I used your llibrary which the code r.getposition(). In the serial monitor ,is the value present is in pulse ? I got 800 value when i rotate in 360 of my encoder. Because im not sure what is  the click means , i just want to comfirm before i proceed with the calculation 😅Btw thank you sir for the suggestion.
