### ISSUE TITLE
ESPRotary.h:20:11: error: 'right' redeclared as different kind of symbol

### ISSUE THREAD

**Issue by BeijingUncle** [LennartHennigs/ESPRotary#42]
When I use both ESPRotary and SdFat in my sketch.

**Comment by LennartHennigs** [comment]
Hey,
I updated the library and added the [enum class feature](https://stackoverflow.com/questions/23288934/c-how-to-have-same-enum-members-name-in-different-enum-names-without-getting-e) to it. This is not in a release yet, but you can checkout the current sources. That should solve your problem.

**Comment by BeijingUncle** [comment]
It works just fine! Thank you for your fast replay!
