### ISSUE TITLE
error complying after upgrading from version 2.0 

### ISSUE THREAD

**Issue by Arielhh** [LennartHennigs/ESPRotary#45]
((r .getDirection()) for right and left is failing to compile.
with version 2.0 the same code is working just fine.

**Comment by LennartHennigs** [comment]
Hey, can you share the code that does not work please?

**Comment by Arielhh** [comment]
It is part of a large code but I think that also the example code stopped working.

void StationControl() {
  if ((r .getDirection()) == right) {
    ++cur_station;
  }
  if ((r.getDirection()) == left) {
    --cur_station;

  }

  if ((cur_station <= (NumberStations)) && (cur_station >= 1)) {
    Rotary_Stations();
  }

  else {

    if (cur_station > (NumberStations)) {
      cur_station = 1;
      Rotary_Stations();
    }

    else if (cur_station < 1) {
      cur_station = (NumberStations);
      Rotary_Stations();
    }
  }
}

**Comment by LennartHennigs** [comment]
Hey, 
in 1.6.1 I encapsulated the direction in a enum:

```
enum class rotary_direction {
  undefined = 0,
  right = 1,
  left = 255
};
```

Therefore, change your code to this:

```
if ((r .getDirection()) == rotary_direction::right) {
  ++cur_station;
}
if ((r.getDirection()) == rotary_direction::left) {
  --cur_station;
}
```
That should solve the compile error.
Cheers
l.

**Comment by Arielhh** [comment]
It is working now :) many thanks for the fix and for sharing this library.

**Comment by LennartHennigs** [comment]
Glad to hear! Thanks and happy tinkering!

**Comment by Arielhh** [comment]
> Glad to hear! Thanks and happy tinkering!

Thanks :)
