### ISSUE TITLE
Encoder counts only up – debounce cap was missing

### ISSUE THREAD

**Issue by Barabba11** [LennartHennigs/ESPRotary#46]
Hi, I don't know what is wrong there, if I disconnect one of the 2 inputs I have no events (right), but If I invert them or change rotation it always increase. ON one direction it only increase, in the other if I go really slow it decrease by 1, but suddenly increase by one
Which parameter should I change? Thanks

I have ESP8266 and a classic mechanical encoder, I'm using D5 and D6

**Comment by LennartHennigs** [comment]
Hey, 
that is kind of hard to tell from afar.
Encoders can have different steps per click values, try setting a different one:

`ESPRotary(byte pin1, byte pin2, byte steps_per_click = 1, int lower_bound = INT16_MIN, int upper_bound = INT16_MAX, int inital_pos = 0, int increment = 1);`

Or, it might be faulty.

**Comment by Barabba11** [comment]
Mate, thank you for your kind help, the reason was the bounces of encoder, connecting condensers 0,1uF solved it. I strongly suggest you to write it on your notes, they sell modules without them so it can happen often that people getting errors
https://github.com/enjoyneering/RotaryEncoder/raw/master/images/rotary_encoder_shematic.png

**Comment by morpheby** [comment]
fyi
The asymmetry (goes mostly up on noise) is due to this line:
https://github.com/LennartHennigs/ESPRotary/blob/797f43660084ba0386c8b0934bff91ded5d7e342/src/ESPRotary.cpp#L215

Changes to two signals of the encoder at the same time should yield 0 steps, as the direction is undefined in this case.
