### ISSUE TITLE
rename hard to understand functions and objects in examples to spot-on self-explaining names

### ISSUE THREAD

**Issue by StefanL38** [LennartHennigs/ESPRotary#47]
As an example I looked into the simple-counterdemo-code
ESPRotary r;

IMHO naming the object with a single letter "r" is even worse than naming it with the same letters as the object-type

The function-names should say **spot-on** what they are doing

`r.setChangedHandler(rotate);`

a motor rotates.

A rotary-encoder is rotated

So what is your function

`void rotate(ESPRotary& r) {
   Serial.println(r.getPosition());
}
`
really doing?

`r.setChangedHandler(printPosition);`

**Comment by LennartHennigs** [comment]
Dear Stefan, let's do this in German:

Vielen Dank für dein Feedback. 

Das hier ist (m)ein Open Source Projekt – d.h. ich und ggf. andere Menschen arbeiten in ihrer freien Zeit daran und stellen das EWrgebnis kostenlos ins Internet. 
Verbesserungen können vorgeschlagen werden und Bugs und Probleme werden hier auch diskutiert.

Fragen sollten aber ernsthaft sein und nicht rhetorisch.
Der Versuch ein Quiz in der "Issues" Sektion zu starten find ich nicht hilfreich.
Wie im echten Leben macht hier auch derTon die Musik.

Ich finde es aber toll, dass Du so eine klare Meinung zu den Dingen hast.
Meine kannst Du ja implizit aus den Funktionsnamen entnehmen.
Wenn die 
LG
Lennart
