### ISSUE TITLE
left/right or no movement at all

### ISSUE THREAD

**Issue by pablopeu** [LennartHennigs/ESPRotary#5]
Hi, is it possible with this library instead of counting up and down like its shown in the examples, to differentiate three states?
say left=-1, right=1 and no movement=0 ?

So the reading will be most of the times 0 and only change when the encoder is turned.

Thanks

**Comment by LennartHennigs** [comment]
Yes, it is. But you don’t need to read states using this library since it offers call back functions to detect when the rotary encoder is used:

r.setLeftRotationHandler(yourFunctionForLeftTurns);
 r.stRightRotationHandler(yourFunctionForRightTurns);

These functions will be called and then you already “know” the direction.  Hope this helps.

**Comment by pablopeu** [comment]
Thanks for the reply, I'm hacking my way into learning arduino, you may have figured this out lol. if I use these functions I can assign -1 or 1 to a variable, but I don't see how I can detect no movement, I modified your example but I don't know where to assign value=0 in it. Thanks
`/////////////////////////////////////////////////////////////////

#include "ESPRotary.h";

/////////////////////////////////////////////////////////////////

#define ROTARY_PIN1	14
#define ROTARY_PIN2	12

/////////////////////////////////////////////////////////////////

ESPRotary r = ESPRotary(ROTARY_PIN1, ROTARY_PIN2);

/////////////////////////////////////////////////////////////////

int8_t value=0; 

void setup() {
  Serial.begin(9600);
  delay(50);
  Serial.println("\n\nSimple Counter");
  
  r.setChangedHandler(rotate);
  r.setLeftRotationHandler(izquierda);
  r.setRightRotationHandler(derecha);
}

void loop() {
  r.loop();
     Serial.println(value);
}

/////////////////////////////////////////////////////////////////

void rotate(ESPRotary& r) {
//value=0; this didn't work
}

void izquierda(ESPRotary& r) {
  value=-1;
}

void derecha(ESPRotary& r) {
  value=1;
}

/////////////////////////////////////////////////////////////////`

**Comment by LennartHennigs** [comment]
When the functions are called movement just took place. So you most likely don’t need a variable. You can just put the things you want to do in the functions itself.

**Comment by pablopeu** [comment]
Yes, that I understood, but since I'm using a single encoder to navigate a menu, sub-menu and inside each sub-menu adjust values with a single encoder and its button I also need to know when its idle or zero in my example. Believe me that I'm embarrased to ask this, but before asking I tried a lot of alternatives using the functions provided but I'm still unable to figure a way to do this.
Thanks!!

**Comment by pablopeu** [comment]
Made it work like I wanted! thanks!!

`/////////////////////////////////////////////////////////////////

#include "ESPRotary.h";

/////////////////////////////////////////////////////////////////

#define ROTARY_PIN1	14
#define ROTARY_PIN2	12

/////////////////////////////////////////////////////////////////

ESPRotary r = ESPRotary(ROTARY_PIN1, ROTARY_PIN2);

/////////////////////////////////////////////////////////////////

int8_t value=0; 
byte flagencoder=false;

void setup() {
  Serial.begin(9600);
  delay(50);
  Serial.println("\n\nSimple Counter");
  
  r.setLeftRotationHandler(izquierda);
  r.setRightRotationHandler(derecha);
}

void loop() {
  r.loop();
  Serial.println(value);

// at the end of the main loop
  if (flagencoder==true) {
    value=0;
    flagencoder=false;
  }
}

/////////////////////////////////////////////////////////////////

void izquierda(ESPRotary& r) {
  value=-1;
  r.resetPosition();
  flagencoder=true;
}

void derecha(ESPRotary& r) {
  value=1;
  r.resetPosition();
  flagencoder=true;
}

/////////////////////////////////////////////////////////////////`

**Comment by CarlosFonseca97** [comment]
Hola pablopeu me gustaría y si no es para ti problema y me guiaras en la elaboración del menú que indicas estabas ejecutando. Gracias y éxitos.
