### ISSUE TITLE
Longer LongClickHandler

### ISSUE THREAD

**Issue by pablopeu** [LennartHennigs/ESPRotary#6]
Hi Lennart, is it possible to adjust the length of a long click? I would like to make it a bit longer to be detected as such. I get false positives from time to time (user fault of course) 

Thanks.

**Comment by LennartHennigs** [comment]
Hi, I have hardcoded the long press delay in the Button2.h. You can change it there. 

https://github.com/LennartHennigs/Button2/blob/master/src/Button2.h

**Comment by pablopeu** [comment]
I totally forgot that buttons and rotary were different libraries... Even after seeing both includes in my mind they were one... That's why I didn't find any reference... BIG FACEPALM. LOL and sorry! Many many thanks!

**Comment by LennartHennigs** [comment]
No problem :-)
