### ISSUE TITLE
[SimpleCounter] Example doesn't work on D1 wemos mini

### ISSUE THREAD

**Issue by tavalin** [LennartHennigs/ESPRotary#8]
I've just tried to use this library and unfortunately it doesn't work on my ESP8266.

I've tried the Simple Counter example and when I upload it to my D1 Mini I get the following continuously:

```
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1392, room 16 
tail 0
chksum 0xd0
csum 0xd0
v3d128e5c
~ld
```
Code attached:

```
/////////////////////////////////////////////////////////////////

#include "ESPRotary.h";

/////////////////////////////////////////////////////////////////

#define ROTARY_PIN1	12
#define ROTARY_PIN2	14

/////////////////////////////////////////////////////////////////

ESPRotary r = ESPRotary(ROTARY_PIN1, ROTARY_PIN2);

/////////////////////////////////////////////////////////////////

void setup() {
  Serial.begin(115200);
  delay(50);
  Serial.println("\n\nSimple Counter");
  
  r.setChangedHandler(rotate);
  r.setLeftRotationHandler(showDirection);
  r.setRightRotationHandler(showDirection);
}

void loop() {
  r.loop();
}

/////////////////////////////////////////////////////////////////

// on change
void rotate(ESPRotary& r) {
   Serial.println(r.getPosition());
}

// on left or right rotattion
void showDirection(ESPRotary& r) {
  Serial.println(r.directionToString(r.getDirection()));
}

/////////////////////////////////////////////////////////////////
```

**Comment by LennartHennigs** [comment]
You have to select the pins you want to use in the example and replace the "12" and "14". 
Please look at the pinout for the right pins to use:
https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/
I recommend using D1 and D2.

**Comment by tavalin** [comment]
Thanks for your reply.  In my case, I want to use GPIO12 and GPIO14 which relate to pins D5 and D6.  I had assumed it required the GPIO number.

I've now tried "12" and "14, "D5" and "D6" and "5" and "6" and all result in resets.

I'm using v1.1.0 btw.

**Comment by LennartHennigs** [comment]
I just pushed a version 1.1.1. Give this a spin. There was a yield() in the loop that caused some problems.

**Comment by tavalin** [comment]
I've just tried v1.1.1 and it's working for me now 👍
