### ISSUE TITLE
Add optional position bounds

### ISSUE THREAD

**Issue by cornfeedhobo** [LennartHennigs/ESPRotary#9]
It would be nice to have the ability to specify that the position never go beyond a certain range, despite further rotations in a certain direction. If you already have a solution for that in the current implementation that I'm not seeing, please let me know. I _may_ attempt a PR, but C++ is not something I touch much.

**Comment by LennartHennigs** [comment]
Thx for submitting a pull request!
I really like the idea and will create a new version in the next couple of days.

**Comment by LennartHennigs** [comment]
Hi, quick note: Your pull request only kind of worked. It didn't take rotary encoders into account that increase the step value greater one. I updated the files accordingly. 

And I added a check whether the ```lower_bound``` is greater 0. 
If so, I set the initial value to the ```lower_bound```.

**Comment by cornfeedhobo** [comment]
@LennartHennigs yeah I ran into that but wasn't sure if that would be considered expected behavior or not. Sorry I should have made a follow up comment this morning. Thanks for patching up both PRs!

**Comment by LennartHennigs** [comment]
No problem.
